### ISSUE TITLE
Zapzap Freeze on start 

### ISSUE THREAD

**Issue by albarro** [zapzap-linux/zapzap#71] opened 2024-04-17 14:37 UTC
Hi
I'm running nobara linux whit kde6 and using the latest flatpak of zapzap.
For some reason every time i try to open zapzap it just freeze and becomes unresponsive
![image](https://github.com/zapzap-linux/zapzap/assets/36165246/9881418d-41c7-4556-a57b-4d08f0de7213)

![image](https://github.com/zapzap-linux/zapzap/assets/36165246/77a0d9ed-aa7f-4597-a69b-903fd489bc11)

**Comment by rafatosta** [comment] 2024-04-17 16:27
> Hi
> I'm running nobara linux whit kde6 and using the latest flatpak of zapzap.
> For some reason every time i try to open zapzap it just freeze and becomes unresponsive
> ![image](https://github.com/zapzap-linux/zapzap/assets/36165246/9881418d-41c7-4556-a57b-4d08f0de7213)
> 
> ![image](https://github.com/zapzap-linux/zapzap/assets/36165246/77a0d9ed-aa7f-4597-a69b-903fd489bc11)
> 

Does not make sense. I'm using it too and I'm not encountering this problem and I can't reproduce it by opening and closing it all the time. 

Let's wait and see if anyone else reports this problem.

**Comment by 4nyNoob** [comment] 2024-04-18 17:22
> Let's wait and see if anyone else reports this problem.

this Someone else has arrived with a verbose terminal output
```
any@any-fedora:~$ flatpak run --verbose com.rtosta.zapzap 
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/any/.local/share/flatpak
F: Opening user flatpak installation at path /home/any/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Skipping parental controls check for app/com.rtosta.zapzap/x86_64/stable since parental controls are disabled globally
F: Opening user flatpak installation at path /home/any/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: /var/lib/flatpak/runtime/org.kde.Platform/x86_64/6.6/b57aa85870fc0ffb4f62ee85df7e4b8d2a4a2f9d245868faa04c0453b6998e21/files/lib32 does not exist
F: Cleaning up unused container id 1647672775
F: Cleaning up per-app-ID state for com.rtosta.zapzap
F: Cleaning up unused container id 4234988581
F: Cleaning up per-app-ID state for com.rtosta.zapzap
F: Allocated instance id 621720416
F: Add defaults in dir /com/rtosta/zapzap/
F: Add locks in dir /com/rtosta/zapzap/
F: Allowing host-fs access
F: Allowing wayland access
F: Allowing pulseaudio access
F: Pulseaudio user configuration file '/home/any/.config/pulse/client.conf': Error opening file /home/any/.config/pulse/client.conf: No such file or directory
F: Running '/usr/bin/bwrap --args 40 /usr/bin/xdg-dbus-proxy --args=42'
F: Running '/usr/bin/bwrap --args 40 zapzap'
warning: queue 0x55f15903a4e0 destroyed while proxies still attached:
  wl_registry@34 still attached
doh set to ""  --  SystemOnly
qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
QPropertyAnimation: you're trying to animate the non-writable property width of your QObject
```
I've reinstalled the flatpak, repaired flatpaks using `flatpak repair` and also used the copr package, both 5.2 and 5.3 are broken on my system, by broken i mean: it just open the window and freeze

**Comment by rafatosta** [comment] 2024-04-18 17:48
> > Let's wait and see if anyone else reports this problem.
> 
> this Someone else has arrived with a verbose terminal output
> ```
> any@any-fedora:~$ flatpak run --verbose com.rtosta.zapzap 
> F: No installations directory in /etc/flatpak/installations.d. Skipping
> F: Opening system flatpak installation at path /var/lib/flatpak
> F: Opening user flatpak installation at path /home/any/.local/share/flatpak
> F: Opening user flatpak installation at path /home/any/.local/share/flatpak
> F: Opening system flatpak installation at path /var/lib/flatpak
> F: Skipping parental controls check for app/com.rtosta.zapzap/x86_64/stable since parental controls are disabled globally
> F: Opening user flatpak installation at path /home/any/.local/share/flatpak
> F: Opening system flatpak installation at path /var/lib/flatpak
> F: /var/lib/flatpak/runtime/org.kde.Platform/x86_64/6.6/b57aa85870fc0ffb4f62ee85df7e4b8d2a4a2f9d245868faa04c0453b6998e21/files/lib32 does not exist
> F: Cleaning up unused container id 1647672775
> F: Cleaning up per-app-ID state for com.rtosta.zapzap
> F: Cleaning up unused container id 4234988581
> F: Cleaning up per-app-ID state for com.rtosta.zapzap
> F: Allocated instance id 621720416
> F: Add defaults in dir /com/rtosta/zapzap/
> F: Add locks in dir /com/rtosta/zapzap/
> F: Allowing host-fs access
> F: Allowing wayland access
> F: Allowing pulseaudio access
> F: Pulseaudio user configuration file '/home/any/.config/pulse/client.conf': Error opening file /home/any/.config/pulse/client.conf: No such file or directory
> F: Running '/usr/bin/bwrap --args 40 /usr/bin/xdg-dbus-proxy --args=42'
> F: Running '/usr/bin/bwrap --args 40 zapzap'
> warning: queue 0x55f15903a4e0 destroyed while proxies still attached:
>   wl_registry@34 still attached
> doh set to ""  --  SystemOnly
> qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
> QPropertyAnimation: you're trying to animate the non-writable property width of your QObject
> ```
> I've reinstalled the flatpak, repaired flatpaks using `flatpak repair` and also used the copr package, both 5.2 and 5.3 are broken on my system, by broken i mean: it just open the window and freeze

I use Fedora Workstation and this problem does not happen with flatpak and copr. Are you sure you didn't make any changes?

**Comment by 4nyNoob** [comment] 2024-04-18 23:36
> > > Let's wait and see if anyone else reports this problem.
> > 
> > 
> > this Someone else has arrived with a verbose terminal output
> > ```
> > any@any-fedora:~$ flatpak run --verbose com.rtosta.zapzap 
> > F: No installations directory in /etc/flatpak/installations.d. Skipping
> > F: Opening system flatpak installation at path /var/lib/flatpak
> > F: Opening user flatpak installation at path /home/any/.local/share/flatpak
> > F: Opening user flatpak installation at path /home/any/.local/share/flatpak
> > F: Opening system flatpak installation at path /var/lib/flatpak
> > F: Skipping parental controls check for app/com.rtosta.zapzap/x86_64/stable since parental controls are disabled globally
> > F: Opening user flatpak installation at path /home/any/.local/share/flatpak
> > F: Opening system flatpak installation at path /var/lib/flatpak
> > F: /var/lib/flatpak/runtime/org.kde.Platform/x86_64/6.6/b57aa85870fc0ffb4f62ee85df7e4b8d2a4a2f9d245868faa04c0453b6998e21/files/lib32 does not exist
> > F: Cleaning up unused container id 1647672775
> > F: Cleaning up per-app-ID state for com.rtosta.zapzap
> > F: Cleaning up unused container id 4234988581
> > F: Cleaning up per-app-ID state for com.rtosta.zapzap
> > F: Allocated instance id 621720416
> > F: Add defaults in dir /com/rtosta/zapzap/
> > F: Add locks in dir /com/rtosta/zapzap/
> > F: Allowing host-fs access
> > F: Allowing wayland access
> > F: Allowing pulseaudio access
> > F: Pulseaudio user configuration file '/home/any/.config/pulse/client.conf': Error opening file /home/any/.config/pulse/client.conf: No such file or directory
> > F: Running '/usr/bin/bwrap --args 40 /usr/bin/xdg-dbus-proxy --args=42'
> > F: Running '/usr/bin/bwrap --args 40 zapzap'
> > warning: queue 0x55f15903a4e0 destroyed while proxies still attached:
> >   wl_registry@34 still attached
> > doh set to ""  --  SystemOnly
> > qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
> > QPropertyAnimation: you're trying to animate the non-writable property width of your QObject
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I've reinstalled the flatpak, repaired flatpaks using `flatpak repair` and also used the copr package, both 5.2 and 5.3 are broken on my system, by broken i mean: it just open the window and freeze
> 
> I use Fedora Workstation and this problem does not happen with flatpak and copr. Are you sure you didn't make any changes?

yes i'm sure, it's my old fedora 39 install, the only thing that's noteworthy on my system is that i'm on nvidia 535(because later versions are crashing some of my apps due to the lack of implicit and explicit sync on the driver)

**Comment by albarro** [comment] 2024-04-20 10:37
Just to share something, i run it with verbose and get the same as @4nyNoob 
```
user@nobara-39:~$ flatpak run --verbose com.rtosta.zapzap 
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/albarro/.local/share/flatpak
F: Opening user flatpak installation at path /home/albarro/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Skipping parental controls check for app/com.rtosta.zapzap/x86_64/stable since parental controls are disabled globally
F: Opening user flatpak installation at path /home/albarro/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: /var/lib/flatpak/runtime/org.kde.Platform/x86_64/6.6/b57aa85870fc0ffb4f62ee85df7e4b8d2a4a2f9d245868faa04c0453b6998e21/files/lib32 does not exist
F: Cleaning up unused container id 658981018
F: Cleaning up per-app-ID state for com.rtosta.zapzap
F: Cleaning up unused container id 1029668501
F: Cleaning up per-app-ID state for com.rtosta.zapzap
F: Cleaning up unused container id 3221685558
F: Allocated instance id 1410221715
F: Add defaults in dir /com/rtosta/zapzap/
F: Add locks in dir /com/rtosta/zapzap/
F: Allowing host-fs access
F: Allowing wayland access
F: Allowing pulseaudio access
F: Pulseaudio user configuration file '/home/albarro/.config/pulse/client.conf': Error opening file /home/albarro/.config/pulse/client.conf: No such file or directory
F: Running '/usr/bin/bwrap --args 39 /usr/bin/xdg-dbus-proxy --args=41'
F: Running '/usr/bin/bwrap --args 39 zapzap'
doh set to ""  --  SystemOnly
qt.gui.imageio: libpng warning: iCCP: known incorrect sRGB profile
QPropertyAnimation: you're trying to animate the non-writable property width of your QObject
```
And i have to add that i only find this problem in nobara, in ubuntu run fine.
Also i try a clean installation of nobara and get the same error.

**Comment by rafatosta** [comment] 2024-04-20 10:47
I installed Fedora KDE on a VM and there is no such problem

**Comment by rafatosta** [comment] 2024-04-20 11:27
Are you using KDE 6?

**Comment by chrostino** [comment] 2024-04-20 13:33
I'm having the same problem;
I am also on Nobara 39 using plasma 6

**Comment by rafatosta** [comment] 2024-04-20 14:06
> I'm having the same problem; I am also on Nobara 39 using KDE 6. Tried uninstalling and deleting app data, then reinstalling (with flatpak) but to no avail. Same as @albarro I don't encounter this problem on my pc running Pop_OS!

Apparently, the problem is between Nobara and KDE 6 and not on Zapzap.

**Comment by Ams-ARB** [comment] 2024-04-22 05:54
Hey, had the same issue. After trying a few things, I figured out a solution that worked for me.

In ~/.bash_profile (if file doesnt exist, search how to create it or if there's an alternative for your distro). Add 'export QT_QPA_PLATFORM=wayland' or 'export QT_QPA_PLATFORM=auto'. Re-login or restart, and it should work.

Also install 'flatseal' and see if wayland is allowed under ZapZap.

**Comment by chrostino** [comment] 2024-04-22 08:27
I tried with the `auto` one and my whole plasma session wouldn't load, it was just a black screen with my cursor (but I could launch apps through keyboard shortcuts), then tried the `wayland` one and nothing happened, zapzap still didn't work

**Comment by rafatosta** [comment] 2024-04-22 12:38
I did an installation of Nobara Kde, updated and installed Zapzap. It is working without the need for modifications.
Note: Works on Wayland and X11 defined in Flatseal

Unfortunately I can't reproduce this problem.
 
![image](https://github.com/zapzap-linux/zapzap/assets/18619894/0b90b414-5a30-4346-bacd-3b753c4c9e3f)

**Comment by chrostino** [comment] 2024-04-22 13:12
I thought the culprit was the update to plasma 6, but I guess I was wrong. I have no clue what could be the cause

**Comment by rafatosta** [comment] 2024-04-22 13:37
> I thought the culprit was the update to plasma 6, but I guess I was wrong. I have no clue what could be the cause

I paired and let the conversations synchronize ... I closed in the middle and opened again. I was closing and opening like a crazy and worked correctly.

**Comment by albarro** [comment] 2024-04-22 15:22
So seeing this i tried something:

- Using the application permissions i disabled Wayland and it works perfectly, (it doesn't scale, but for what i understand is not the application fault)
![image](https://github.com/zapzap-linux/zapzap/assets/36165246/cf954ff1-8037-431c-b633-66be5a5fab72)

- Enabling Wayland makes the application irresponsible again
![image](https://github.com/zapzap-linux/zapzap/assets/36165246/8f644b77-eb0d-4c05-a3fb-71e53b1461cb)

Seems the problems is in Wayland and nobara

**Comment by chrostino** [comment] 2024-04-22 17:15
> So seeing this i tried something:
> 
>     * Using the application permissions i disabled Wayland and it works perfectly, (it doesn't scale, but for what i understand is not the application fault)
>       ![image](https://private-user-images.githubusercontent.com/36165246/324513154-cf954ff1-8037-431c-b633-66be5a5fab72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3OTk2NzAsIm5iZiI6MTcxMzc5OTM3MCwicGF0aCI6Ii8zNjE2NTI0Ni8zMjQ1MTMxNTQtY2Y5NTRmZjEtODAzNy00MzFjLWI2MzMtNjZiZTVhNWZhYjcyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDE1MjI1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5ZTg4NWY3NWVlMGM5NGM1ZWY3ZGZmNTkxMGY2ZWFjZWY0MDNjMzczODY0YTQ4N2QzZjRiOTgwZGVmZjk4ZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bo8l-eAQEnjN-NbnPoWEnT7bHko9xO0RVAx77hNhH4c)
> 
>     * Enabling Wayland makes the application irresponsible again
>       ![image](https://private-user-images.githubusercontent.com/36165246/324517258-8f644b77-eb0d-4c05-a3fb-71e53b1461cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3OTk2NzAsIm5iZiI6MTcxMzc5OTM3MCwicGF0aCI6Ii8zNjE2NTI0Ni8zMjQ1MTcyNTgtOGY2NDRiNzctZWIwZC00YzA1LWEzZmItNzFlNTNiMTQ2MWNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDE1MjI1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjMjQzODZiNmYzZmQ2N2I4MmUwMmFmYzEyMGU0YzhmZGYyODhlNTVjYjk5Zjc3ZTU4ZGE2YTliNmU1Y2NmYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.To7uqO1zcFcynk-Zns6UoCKvqZvHsYpBvEFtVQcW2U4)
> 
> 
> Seems the problems is in Wayland and nobara

can confirm, disabling wayland makes the app work again non problem

**Comment by rafatosta** [comment] 2024-04-23 00:58
You guys have NVidea, right?

**Comment by 4nyNoob** [comment] 2024-04-23 01:47
it's always nvidia, i'm waiting for driver 555 to add explicit sync ***finally*** and i hope that it does work well this time, unlike 545... and 550

**Comment by chrostino** [comment] 2024-04-23 09:24
550 here. Average nvidia experience

**Comment by albarro** [comment] 2024-04-23 15:04
> You guys have nvidia, right?
> 
> Maybe she is the problem... As always 😅

Yep, i have nvidia.
Sorry for the trouble

**Comment by rafatosta** [comment] 2024-04-23 21:01
For those of you who use Nobara, try Copr

https://copr.fedorainfracloud.org/coprs/rafatosta/zapzap/

**Comment by 4nyNoob** [comment] 2024-04-24 19:19
![image](https://github.com/zapzap-linux/zapzap/assets/113947854/414b4b95-a16d-4b02-8f35-5764de6eb031)
Disabling wayland solves the issue to me

**Comment by rafatosta** [comment] 2024-04-29 12:19
![image](https://github.com/zapzap-linux/zapzap/assets/18619894/e4aa1273-0f67-4ee6-8e39-c71435a3a014)

**Closed by rafatosta** 2024-04-29 12:19 UTC

**Comment by prodrigestivill** [comment] 2024-04-30 08:47
Upstream bug report: https://bugreports.qt.io/browse/QTBUG-124174

Adds also this workarround until is fixed in QT library.
`QT_OPENGL_NO_SANITY_CHECK=1`

**Comment by rafatosta** [comment] 2024-04-30 10:06
> Upstream bug report: https://bugreports.qt.io/browse/QTBUG-124174
> 
> Adds also this workarround until is fixed in QT library.
> `QT_OPENGL_NO_SANITY_CHECK=1`
> 

Thanks! It looks like Qt 6.7 solves this problem. This week I believe I will be able to apply it on zapzap
